### ISSUE TITLE
Command fails under Windows

### ISSUE THREAD

**Issue by nexusstar** [benawad/create-graphql-api#3]
I am unable to use it under Windows. 

OS: windows 10 - 1903
node: 13..0
npm: 6.13.1
Command is run on PowerShell Core 6.2
And node is installed with scoop.
 
here is the output from `yarn create graphql-api` because it's with more information 
```bash
UniBit $ yarn create graphql-api typescript-graphql-crud-try
yarn create v1.19.1
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-graphql-api@1.2.4" with binaries:
      - create-graphql-api
yarn install v1.19.1
warning package.json: No license field
warning ..\..\..\package.json: No license field
info No lockfile found.
warning myapi@0.0.1: No license field
[1/4] Resolving packages...
warning nodemon > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > type-graphql@0.17.5" has unmet peer dependency "@types/graphql@^14.0.7".
[4/4] Building fresh packages...
[1/5] ⠂ core-js
[-/5] ⠂ waiting...
[3/5] ⠂ sqlite3
[4/5] ⠂ type-graphql
error C:\Users\p.nikov\workspace\UniBit\typescript-graphql-crud-try\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\p.nikov\workspace\UniBit\typescript-graphql-crud-try\node_modules\sqlite3




child_process.js:642
    throw err;
    ^

Error: Command failed: yarn install
    at checkExecSyncError (child_process.js:603:11)
    at execSync (child_process.js:639:15)
    at Object.<anonymous> (C:\Users\p.nikov\scoop\persist\yarn\global\node_modules\create-graphql-api\src\index.js:69:3)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15744,
  stdout: null,
  stderr: null
}
error Command failed.
Exit code: 1
Command: C:\Users\p.nikov\scoop\apps\yarn\current\global\bin\create-graphql-api
Arguments: typescript-graphql-crud-try
Directory: C:\Users\p.nikov\workspace\UniBit
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
Error from `npx create-graphql-api`:
```bash
UniBit $ npx create-graphql-api typescript-graphql
yarn install v1.19.1
warning package.json: No license field
warning ..\..\..\package.json: No license field
info No lockfile found.
warning myapi@0.0.1: No license field
[1/4] Resolving packages...
warning nodemon > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > type-graphql@0.17.5" has unmet peer dependency "@types/graphql@^14.0.7".
[4/4] Building fresh packages...
[1/5] ⠂ core-js
[2/5] ⠂ @apollo/protobufjs
[3/5] ⠂ sqlite3
[4/5] ⠂ type-graphql
error C:\Users\p.nikov\workspace\UniBit\typescript-graphql\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\p.nikov\workspace\UniBit\typescript-graphql\node_modules\sqlite3




Command failed: yarn install
```

**Comment by benawad** [comment]
Looks like the `yarn install` failed. Does the directory still get created for you? If so, could you try running `yarn install` or `npm install` in there and see if the same error occurs.

**Comment by nexusstar** [comment]
That is what I try first.  
The directory is created and when I run `yarn install` it failed with the same error. 
It looks line this is known issue with `node-pre-gyp` and is not related to your project sorry for that.  The #https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by benawad** [comment]
no worries, `node-pre-gyp` is a trouble maker

**Comment by nexusstar** [comment]
I found a workaround. Downgrade node to latest LTS and installing `node-pre-gyp` as global package solve this for me.
